DROP TABLE IF EXISTS users CASCADE;

/* Users Table*/
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);



